# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "dqQAdHwDOX9MMqb2akwFDT2gohPD1bOHIIqS5vA+vrankFzUeRGdI9SFqJoUNxYjyn9hpUdHQGqdsvzIh1+Ef+HD8ahziOlssaLWeUsaCrC1C2wxD+zQyETIZfwaAE8lW6kDoXdBvIsMtaiWObabSK+cEgG6SXIBOyhYu7MMeDwK1JQe8qVaIASFIMsxjGhvRuiW+BcdCccFGOmiTxPB8+D9EZ7oxsHUUQaE42XEs5TFwc/+PpJzl0am8UbOySr85lTEYGUNEK4H5K+78G4KydaXv79+4+1pTNvoX467yk/gJ1QRi05jbBQ9rR14Gxb41S4E4xyHK8GadNz5FujPxDvZ/wl6YXMet+g7YwXDydfKyClcyXIyPZAUfwDsP/DPJSFuk5Do6dod/nGubBxdzYkK8pZCKVQO/A0xJ9cloIlMijAbkriEpBrZ69hom0BxQdmQE9ixs+DZdCc+ePgoahufdVjDWwp6QrDJnQ5enWHkmMdJopEQQ8NO/YgpKSlqt5oDfo9hazgfA565/KfySFGIHtkTEWofu1PtS3iDUMDXviK0M8FYvBTcEqcm1b4fFzu+RTy18hJ4+krbGkEP18zFLXFgH2JG0lUyH66n8kaPJ55Vroa5TpEZe+Bxa74IaKMzc4jwAKf7kcWeN9oSXI3AAeD/+K+vyxeXGE3uZ+U="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
