travis:
  secure:
    BINSTAR_TOKEN: DPT7ZsjvTI3jYHpB9eKfp0FrpuuQqasLviouNau7HGuprq858PJ4RpmcR52/+0dOgYrgJ8XXjXWKuX+ldzWj8X1WHekFZE0LlWnR6xwrCrNK5ivRNTktRMNupBa3E/mcRe1XbyXsG3G0ac4NQmjz9dZn2b6zsonc7zvi5dhWiwQiKXTlrlSv5e4aVQ/EvSjZAcuKtzjajMnx09bzFXDH67cNOnwA01TIDxTUeGTT3qjsBRaEAPqBeQCzRPzKzN5s8hsfpFHOMXCBVl0yC/v5mjGn3O0RMuf2ZXCAvmminfaj0v5X9jl+OvfvTGw81fcUTgaRP47EKbU91b40xeviAuVujlCPTZ6fgaVzpiD26yJPwcZpuGDgyCMOH4Ye2JP8GSUCNmzXNreBoigqlM/kDGOMFSXx9Yn6B6SPeJXWZskFllmzI16MbFU8kjjXUYaxLswdfg4HpBNLJw/4txA74X9l0kVgij+8syWYADDHu34fXaLi+D4AeLXlmQtwfiXHFIssVttgkRFiaskptIORiTDkyAaBjPiEBLb/fswzyhrT6uh7ly2K6DvaimuTcw+hKzFH5r10tIRLfWPX1O+RiTWU+oagaDkf+Gg71/HCtKgarqD8aT7bEl+bzLNLEbBnTjRjx2T5WimQqO072nl7E7jOzNX1/fbcBYOoDlP/5+8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
