travis:
  secure:
    BINSTAR_TOKEN: dqQAdHwDOX9MMqb2akwFDT2gohPD1bOHIIqS5vA+vrankFzUeRGdI9SFqJoUNxYjyn9hpUdHQGqdsvzIh1+Ef+HD8ahziOlssaLWeUsaCrC1C2wxD+zQyETIZfwaAE8lW6kDoXdBvIsMtaiWObabSK+cEgG6SXIBOyhYu7MMeDwK1JQe8qVaIASFIMsxjGhvRuiW+BcdCccFGOmiTxPB8+D9EZ7oxsHUUQaE42XEs5TFwc/+PpJzl0am8UbOySr85lTEYGUNEK4H5K+78G4KydaXv79+4+1pTNvoX467yk/gJ1QRi05jbBQ9rR14Gxb41S4E4xyHK8GadNz5FujPxDvZ/wl6YXMet+g7YwXDydfKyClcyXIyPZAUfwDsP/DPJSFuk5Do6dod/nGubBxdzYkK8pZCKVQO/A0xJ9cloIlMijAbkriEpBrZ69hom0BxQdmQE9ixs+DZdCc+ePgoahufdVjDWwp6QrDJnQ5enWHkmMdJopEQQ8NO/YgpKSlqt5oDfo9hazgfA565/KfySFGIHtkTEWofu1PtS3iDUMDXviK0M8FYvBTcEqcm1b4fFzu+RTy18hJ4+krbGkEP18zFLXFgH2JG0lUyH66n8kaPJ55Vroa5TpEZe+Bxa74IaKMzc4jwAKf7kcWeN9oSXI3AAeD/+K+vyxeXGE3uZ+U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
